name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v0.0.0 
    - name: Install Selenium
      run: |
          sudo pip3 install selenium
    - name: ChromeWebDriver
      run: |
          cat <<EOF >> test.py
          from selenium import webdriver
          from selenium.webdriver.chrome.options import Options
          options = Options()
          options.add_argument("--headless")
          options.add_argument('--no-sandbox')
          options.add_argument('--disable-gpu')
          options.add_argument('--disable-dev-shm-usage')       
          options.add_argument('--remote-debugging-port=9222')
          driver = webdriver.Chrome(chrome_options=options, executable_path='/usr/bin/chromedriver')       
          EOF

          python3 test.py 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test 'AnimalAdoption.Web.Portal.UnitTests/AnimalAdoption.Web.Portal.UnitTests.csproj' --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: artifact # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: '/publish' 
        # The desired behavior if no files are found using the provided path.   
      
      
      
      continue-on-error: true
