name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v0.0.0 
    - name: Install Selenium
      run: |
          sudo pip3 install selenium
    - name: ChromeWebDriver
      run: |
          cat <<EOF >> test.py
          from selenium import webdriver
          from selenium.webdriver.chrome.options import Options
          options = Options()
          options.add_argument("--headless")
          options.add_argument('--no-sandbox')
          options.add_argument('--disable-gpu')
          options.add_argument('--disable-dev-shm-usage')
          options.add_argument('disable-infobars')
          options.add_argument("--disable-extensions")
          driver = webdriver.Chrome(chrome_options=options, executable_path='/usr/bin/chromedriver')
          driver.get("http://github.com/")
          print ('Page title is ' + driver.title)
          EOF

          python3 test.py
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      continue-on-error: true
